### Get all books
GET http://localhost:3500/books

### Get book by id
GET http://localhost:3500/books/9780451524935

### Insert book
POST http://localhost:3500/books HTTP/1.1
content-type: application/json

{
  "_id": "9780061120084",
  "title": "To Kill a Mockingbird",
  "author": "Harper Lee",
  "genre": "Drama",
  "year": "1960"
}

### Update book
PUT http://localhost:3500/books/9780061120084 HTTP/1.1
content-type: application/json

{
  "title": "To Kill a Mockingbird",
  "author": "Harper Lee",
  "genre": "Drama",
  "year": "1961"
}

###Delete book
DELETE http://localhost:3500/books/9780061120084